version: '3'
services:
  python:
    build: .
    image: miranda:20200430
    ports:
      - '55555:55555'
    volumes:
      - .:/miranda
    stdin_open: true
    tty: true
    command: ['python', '/miranda/app/core.py']
    restart: unless-stopped
    stop_signal: SIGINT
