services:
  miranda:
    command: sh -c 'pip install -Ur requirements.txt && python -m miranda'
    image: python:3-alpine
    ports:
      - '55555:55555'
    restart: 'no'
    stdin_open: true
    stop_signal: SIGINT
    tty: true
    volumes:
      - ./config.ini:/root/.config/miranda/config.ini:ro
      - ./twitch.json:/root/.config/miranda/twitch.json
      - .:/miranda
    working_dir: /miranda
