version: '3'
services:
  python:
    image: python:3-alpine
    ports:
      - '55555:55555'
    volumes:
      - .:/miranda
    stdin_open: true
    tty: true
    command: sh /miranda/entrypoint.sh
    restart: unless-stopped
