services:
  miranda:
    build: .
    command: python -m miranda
    image: miranda:202509
    ports:
      - '55555:55555'
    restart: 'no'
    stdin_open: true
    stop_signal: SIGINT
    tty: true
    volumes:
      - ~/.config/miranda/:/root/.config/miranda/
