[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
dependencies = [
    "aiohttp==3.9.1",
    "websockets==12.0",
]
license = {file = "LICENSE"}
name = "miranda"
readme = "README.md"
requires-python = ">=3.11"
version = "20230327"
